name: Build Java File

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Define a list of Operating Systems to run on
        os: [ubuntu-latest, windows-latest]
        java-version: [11, 17, 21] # Common LTS versions

    steps:
    - uses: actions/checkout@v3

    - name: Validate the syntax
      run: mvn validate

    - name: Do a clean Package and install
      run: mvn clean install
      
  
